// <auto-generated />
using System;
using LearningManagementSystem.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.AddressDetail", b =>
                {
                    b.Property<Guid>("Address_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoorNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandMark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrimaryInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Address_Id");

                    b.HasIndex("PrimaryInfoId");

                    b.ToTable("AddressDetails");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.BankDetail", b =>
                {
                    b.Property<Guid>("Bank_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AccountNo")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSC_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrimaryInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Bank_Id");

                    b.HasIndex("PrimaryInfoId");

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.ContactDetail", b =>
                {
                    b.Property<Guid>("Contact_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ContactNo")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrimaryInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Contact_Id");

                    b.HasIndex("PrimaryInfoId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.EducationDetail", b =>
                {
                    b.Property<Guid>("Education_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EducationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("PrimaryInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearOfPassing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Education_Id");

                    b.HasIndex("PrimaryInfoId");

                    b.ToTable("EducationDetails");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.ExperienceDetail", b =>
                {
                    b.Property<Guid>("Experience_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfJoing")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRelieving")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrimaryInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Experience_Id");

                    b.HasIndex("PrimaryInfoId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.PrimaryInfo", b =>
                {
                    b.Property<Guid>("PrimaryInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateOfJoining")
                        .HasColumnType("date");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Id")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Employee_Name")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SecondaryInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PrimaryInfoId");

                    b.ToTable("PrimaryInfos");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.SecondaryInfo", b =>
                {
                    b.Property<Guid>("Secondary_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AadharNo")
                        .HasColumnType("bigint");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrimaryInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Secondary_Id");

                    b.HasIndex("PrimaryInfoId")
                        .IsUnique();

                    b.ToTable("SecondaryInfos");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.TechnicalSkill", b =>
                {
                    b.Property<Guid>("Technical_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkillRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Technical_Id");

                    b.ToTable("TechnicalSkills");
                });

            modelBuilder.Entity("PrimaryInfoTechnicalSkills", b =>
                {
                    b.Property<Guid>("PrimaryInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TechnicalSkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PrimaryInfoId", "TechnicalSkillId");

                    b.HasIndex("TechnicalSkillId");

                    b.ToTable("PrimaryInfoTechnicalSkills");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.AddressDetail", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.Entity.PrimaryInfo", "PrimaryInfo")
                        .WithMany("AddressDetails")
                        .HasForeignKey("PrimaryInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryInfo");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.BankDetail", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.Entity.PrimaryInfo", "PrimaryInfo")
                        .WithMany("BankDetails")
                        .HasForeignKey("PrimaryInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryInfo");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.ContactDetail", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.Entity.PrimaryInfo", "PrimaryInfo")
                        .WithMany("ContactDetails")
                        .HasForeignKey("PrimaryInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryInfo");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.EducationDetail", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.Entity.PrimaryInfo", "PrimaryInfo")
                        .WithMany("EducationDetails")
                        .HasForeignKey("PrimaryInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryInfo");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.ExperienceDetail", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.Entity.PrimaryInfo", "PrimaryInfo")
                        .WithMany("ExperienceDetails")
                        .HasForeignKey("PrimaryInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryInfo");
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.SecondaryInfo", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.Entity.PrimaryInfo", "PrimaryInfo")
                        .WithOne("SecondaryInfo")
                        .HasForeignKey("LearningManagementSystem.Models.Entity.SecondaryInfo", "PrimaryInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryInfo");
                });

            modelBuilder.Entity("PrimaryInfoTechnicalSkills", b =>
                {
                    b.HasOne("LearningManagementSystem.Models.Entity.PrimaryInfo", null)
                        .WithMany()
                        .HasForeignKey("PrimaryInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningManagementSystem.Models.Entity.TechnicalSkill", null)
                        .WithMany()
                        .HasForeignKey("TechnicalSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearningManagementSystem.Models.Entity.PrimaryInfo", b =>
                {
                    b.Navigation("AddressDetails");

                    b.Navigation("BankDetails");

                    b.Navigation("ContactDetails");

                    b.Navigation("EducationDetails");

                    b.Navigation("ExperienceDetails");

                    b.Navigation("SecondaryInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
